version: 0.2

phases:
  pre_build:
    commands:
      - echo "ðŸ”§ Installing Rust..."
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source ~/.cargo/env
      - rustup target add x86_64-unknown-linux-gnu
      - echo "ðŸ“¦ Installing cross-compilation dependencies..."
      - yum update -y
      - yum install -y gcc gcc-c++ make jq wget unzip
      - echo "ðŸ”§ Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
      - unzip terraform_1.13.1_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - terraform version
      
  build:
    commands:
      - echo "ðŸ”¨ Building Rust binary for Lambda..."
      - source ~/.cargo/env
      - cargo build --release --target x86_64-unknown-linux-gnu
      - echo "ðŸ“¦ Creating Lambda deployment package..."
      - cp target/x86_64-unknown-linux-gnu/release/dejafoo-proxy bootstrap
      - zip dejafoo-lambda.zip bootstrap
      - rm bootstrap
      - echo "âœ… Build completed successfully"

  post_build:
    commands:
      - echo "ðŸš€ Deploying Lambda function..."
      - echo "ðŸ“¦ Updating Lambda function with new code..."
      - |
        aws lambda update-function-code \
          --function-name dejafoo-proxy-prod \
          --zip-file fileb://dejafoo-lambda.zip
      - echo "â³ Waiting for function update to complete..."
      - |
        aws lambda wait function-updated \
          --function-name dejafoo-proxy-prod
      - echo "âœ… Lambda function updated successfully"
      - echo "ðŸ“‹ Getting function info..."
      - |
        aws lambda get-function \
          --function-name dejafoo-proxy-prod \
          --query 'Configuration.{FunctionName:FunctionName,Runtime:Runtime,LastModified:LastModified,FunctionUrl:FunctionUrl}' \
          > deployment-info.json
      - echo "âœ… Deployment completed successfully"

artifacts:
  files:
    - dejafoo-lambda.zip
    - deployment-info.json
  name: dejafoo-deployment-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - ~/.cargo/registry/**
    - ~/.cargo/git/**
    - target/**

env:
  variables:
    RUST_BACKTRACE: 1
