# Allowlist configuration for dejafoo
# Defines allowed upstream hosts and blocked paths

# Allowed upstream hosts (domains/IPs that can be proxied to)
allowed_hosts:
  - api.example.com
  - api.staging.example.com
  - api.dev.example.com
  - localhost
  - 127.0.0.1
  - 0.0.0.0
  - 10.0.0.0/8      # Private network range
  - 172.16.0.0/12   # Private network range
  - 192.168.0.0/16  # Private network range

# Allowed URL schemes
allowed_schemes:
  - https
  - http

# Blocked paths (paths that should never be proxied)
blocked_paths:
  - /admin/*
  - /internal/*
  - /debug/*
  - /metrics
  - /health/internal
  - /status/internal
  - /_internal/*
  - /.*\.env
  - /.*\.config
  - /.*\.log
  - /.*\.sql
  - /.*\.db
  - /.*\.bak
  - /.*\.backup

# Blocked query parameters (requests with these params will be rejected)
blocked_query_params:
  - password
  - secret
  - token
  - key
  - auth
  - credential
  - passwd
  - pwd

# Blocked headers (requests with these headers will be rejected)
blocked_headers:
  - x-forwarded-host
  - x-forwarded-proto
  - x-forwarded-port
  - x-real-ip
  - x-original-url
  - x-rewrite-url

# Rate limiting configuration
rate_limiting:
  enabled: true
  requests_per_minute: 1000
  burst_size: 100
  window_size: 60  # seconds

# Request size limits
request_limits:
  max_body_size: 10485760  # 10MB
  max_header_size: 8192    # 8KB
  max_url_length: 2048     # 2KB

# Timeout configuration
timeouts:
  connect_timeout: 10      # seconds
  read_timeout: 30         # seconds
  write_timeout: 30        # seconds
  total_timeout: 60        # seconds

# Security headers to add to responses
security_headers:
  x-frame-options: DENY
  x-content-type-options: nosniff
  x-xss-protection: "1; mode=block"
  strict-transport-security: "max-age=31536000; includeSubDomains"
  content-security-policy: "default-src 'self'"

# CORS configuration
cors:
  enabled: true
  allowed_origins:
    - https://example.com
    - https://www.example.com
    - https://staging.example.com
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization
    - X-Requested-With
    - X-API-Key
  max_age: 86400  # 24 hours

# Logging configuration
logging:
  level: INFO
  format: json
  include_headers: false
  include_body: false
  sensitive_headers:
    - authorization
    - x-api-key
    - cookie
    - set-cookie

# Monitoring and alerting
monitoring:
  enabled: true
  metrics_endpoint: /metrics
  health_check_endpoint: /health
  alert_on_errors: true
  alert_on_high_latency: true
  high_latency_threshold: 5000  # milliseconds

# Cache configuration
cache:
  enabled: true
  default_ttl: 3600  # 1 hour
  max_entries: 10000
  cleanup_interval: 300  # 5 minutes
  compression_enabled: true
